codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 5%
        paths:
          - "src/**"

ignore:
  - "node_modules/**"
  - "**/node_modules/**"
  - "../ruri/**"
