import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const jsPath = join(__dirname, "../../editor/dist/ez-portable-text.umd.js");
const cssPath = join(__dirname, "../../editor/dist/ez-portable-text.umd.css");

try {
  const jsContent = readFileSync(jsPath, "utf8");
  const cssContent = readFileSync(cssPath, "utf8");

  const destDir = join(__dirname, "../src/assets");
  mkdirSync(destDir, { recursive: true });

  const tsContent = `// This file is auto-generated by scripts/compile-assets.ts. Do not edit directly.
export const EZ_PORTABLE_TEXT_JS = ${JSON.stringify(jsContent)};
export const EZ_PORTABLE_TEXT_CSS = ${JSON.stringify(cssContent)};
`;

  writeFileSync(join(destDir, "ez-portable-text-bundle.ts"), tsContent, "utf8");
  console.log(
    "✅ Asset compilation complete: src/assets/ez-portable-text-bundle.ts generated.",
  );
} catch (err: any) {
  console.error("❌ Failed to compile assets:", err);
  process.exit(1);
}
